import openai
import os
from dotenv import load_dotenv

load_dotenv()

class MedicalReportGenerator:
    def __init__(self):
        openai.api_key = os.getenv('OPENAI_API_KEY')
        self.cancer_info = {
            'adenocarcinoma': {
                'description': 'Most common type of lung cancer, typically found in outer areas of lungs',
                'treatment': 'Surgery, chemotherapy (Cisplatin/Paclitaxel), targeted therapy, immunotherapy'
            },
            'large.cell.carcinoma': {
                'description': 'Aggressive form of non-small cell lung cancer with rapid growth',
                'treatment': 'Surgery, radiation therapy, chemotherapy (Carboplatin/Paclitaxel)'
            },
            'squamous.cell.carcinoma': {
                'description': 'Typically develops in central airways, strongly linked to smoking',
                'treatment': 'Surgery, radiation therapy, chemotherapy (Cisplatin-based regimens)'
            },
            'normal': {
                'description': 'No malignant tissue detected in the analyzed CT scan',
                'treatment': 'Continue regular screening and maintain healthy lifestyle'
            }
        }
    
    def get_basic_recommendation(self, cancer_type):
        """Get basic treatment recommendation"""
        return self.cancer_info.get(cancer_type, {}).get('treatment', 'Consult oncologist for treatment plan')
    
    def generate_medical_report(self, prediction, confidence, cancer_type):
        """Generate comprehensive medical report using GPT-3.5"""
        try:
            cancer_desc = self.cancer_info.get(cancer_type, {}).get('description', 'Unknown cancer type')
            basic_treatment = self.get_basic_recommendation(cancer_type)
            
            prompt = f"""
            Generate a professional medical report for a lung cancer CT scan analysis with the following details:
            
            Prediction: {prediction}
            Confidence Score: {confidence:.2f}
            Cancer Type: {cancer_type.replace('.', ' ').title()}
            
            Include the following sections:
            1. Summary of Findings
            2. AI Confidence Assessment
            3. Detailed Cancer Type Information
            4. Clinical Recommendations
            5. Important Disclaimer
            
            Keep the report professional, concise, and include appropriate medical terminology.
            """
            
            response = openai.ChatCompletion.create(
                model="gpt-3.5-turbo",
                messages=[
                    {"role": "system", "content": "You are a medical AI assistant generating formal radiology reports."},
                    {"role": "user", "content": prompt}
                ],
                max_tokens=800,
                temperature=0.3
            )
            
            return response.choices[0].message.content
            
        except Exception as e:
            # Fallback report if OpenAI API fails
            return self._generate_fallback_report(prediction, confidence, cancer_type)
    
    def _generate_fallback_report(self, prediction, confidence, cancer_type):
        """Generate fallback report when API is unavailable"""
        cancer_desc = self.cancer_info.get(cancer_type, {}).get('description', 'Unknown cancer type')
        basic_treatment = self.get_basic_recommendation(cancer_type)
        
        report = f"""
LUNG CANCER CT SCAN ANALYSIS REPORT

SUMMARY OF FINDINGS:
The AI analysis has identified the lung tissue as: {prediction.replace('.', ' ').title()}

AI CONFIDENCE ASSESSMENT:
Model Confidence: {confidence:.1%}
Analysis Method: EfficientNet-B4 Deep Learning Model

DETAILED CANCER TYPE INFORMATION:
{cancer_desc}

CLINICAL RECOMMENDATIONS:
{basic_treatment}

IMPORTANT DISCLAIMER:
This analysis is generated by an AI system for research purposes only. 
This report should not be used as a substitute for professional medical diagnosis 
or treatment. Please consult with a qualified healthcare provider for proper 
medical evaluation and treatment planning.

Generated by: Lung Cancer AI Classifier System
Date: {__import__('datetime').datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
        """
        
        return report.strip()